### PR TITLE
To-Do-List/Notes App

### PR DESCRIPTION
**Pull request by zolwethu**
Simple to do list app, where you can write, update, mark as done and delete notes

### CODE REVIEW

**Review by NuffSaid-Bore — CHANGES_REQUESTED** [review]
@zolwethu try to also include steps on how to open the project like after cloning the project. like change directory to the projects and opening it in vs code for an example.

**Review by BAHLEMAJOLA — CHANGES_REQUESTED** [review]
@zolwethu Please increase the container size to ensure that all the flexbox elements are displayed correctly.

**Comment by zolwethu** [comment]
@NuffSaid-Bore I have included the steps on how to clone the project. navigating to the project directory and opening it in vs code.

**Comment by zolwethu** [comment]
@BAHLEMAJOLA I have increased the width of the container so that all first row tiles display fully without the need for scrolling, user experienced is improved. Please check it again and let me know if there's more changes i should do

**Review by BAHLEMAJOLA — APPROVED** [review]
ohhh great now you can merge popoooo :muscle: 👍

**Review by NuffSaid-Bore — APPROVED** [review]
looks good, will let you know if there are some more changes

**Pull request merged**
